name: Publish Docker Image to GHCR

on:
  push

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set image tag
        id: set-tag
        run: |
          TAG="${{ github.ref_name }}"
          TAG="${TAG//\//-}"
          echo "tag=${TAG}" >> $GITHUB_OUTPUT
      - name: Build and push the image
        run: |
          docker login --username goingoffroading --password ${{ secrets.GH_PAT }} ghcr.io
          docker build . --tag ghcr.io/goingoffroading/rsync:${{ steps.set-tag.outputs.tag }}
          docker push ghcr.io/goingoffroading/rsync:${{ steps.set-tag.outputs.tag }}